[build]
  command = "cd frontend && npm install && npm run build"
  publish = "frontend/dist/zie-frontend"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/api/*"
  [headers.values]
    Cache-Control = "no-cache, no-store, must-revalidate"
